import os

PYTHONPATH = os.environ['PYTHONPATH']
RAW_DATA_PATH = f"{PYTHONPATH}{os.environ['RAW_DATA_PATH']}"
PROCESSED_DATA_PATH = f"{PYTHONPATH}{os.environ['PROCESSED_DATA_PATH']}"
PREDICTIONS_PATH = f"{PYTHONPATH}{os.environ['PREDICTIONS_PATH']}"
MODEL_PATH = f"{PYTHONPATH}{os.environ['MODEL_PATH']}"
